create table app_user (
                          balance bigint,
                          user_id bigint not null,
                          username varchar(50),
                          primary key (user_id)
);

create table bet (
                     odds_against float(53),
                     odds_for float(53),
                     outcome boolean,
                     closing timestamp(6) with time zone,
                     creator_id bigint not null,
                     bet_id uuid not null,
                     name varchar(256) not null unique,
                     message_id varchar(255),
                     primary key (bet_id)
);

create table placed_bet (
                            decision smallint check (decision between 0 and 1),
                            amount bigint not null,
                            bet_placed_id bigint generated by default as identity,
                            user_id bigint not null,
                            bet_id uuid not null,
                            primary key (bet_placed_id)
);

alter table if exists bet
    add constraint FKsojfhmcvg47iser9jxc8prkcx
        foreign key (creator_id)
            references app_user;

alter table if exists placed_bet
    add constraint FKhj5mjl2fwd5bn52vfutydkiit
        foreign key (bet_id)
            references bet;

alter table if exists placed_bet
    add constraint FK57ifno2g8e71w9p2kq9io803e
        foreign key (user_id)
            references app_user;
